default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: K0uki0307
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: MS2IN

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: MS2IN_production
  username: MS2IN
  password: <%= ENV['MS2IN_DATABASE_PASSWORD'] %>
